### ISSUE TITLE
Use Repo2docker in travis-ci

### ISSUE THREAD

**Issue by lsetiawan** [BiG-CZ/wshp2017_tutorial_content#2]
@ocefpaf I'll need your help in setting up travisci for this one.

I was thinking of using https://github.com/jupyter/repo2docker to create Docker image of the repo, then auto push to the odm2 repo in docker hub for images. I would like to automate this so that when someone update their tutorial the changes propagates automatically to the docker image, then my jupyterhub in AWS can get updated easily. :) Thanks!

**Comment by lsetiawan** [comment]
@ocefpaf Nevermind, after looking into things further, it seems like the AWS jupyterhub will not be able to update the contents from the Docker image when there is a persistent volume. We'll just use git to update the files. I think that we'll hardly update the actual environment, so no need for travis ci! Thanks anyways. 😄 Sorry for the extra noise.

**Comment by ocefpaf** [comment]
No problem.

PS: I am not an expert on this, but maybe you should ask on the binder gitter channel how they do that.
