### ISSUE TITLE
help testing jupyterhub log in, default files

### ISSUE THREAD

**Issue by emiliom** [BiG-CZ/wshp2017_tutorial_content#4]
@ocefpaf, as you know @lsetiawan has been working on setting up an AWS-based JupyterHub for our BiG CZ workshop. It's mostly ready, though I'm sure there are still tweaks to be made.

Don is on leave for the rest of the week, [doing good for Seattle](http://seattlecenter.org/skcclinic/) :open_mouth: 

He mentioned that maybe you could help us do some testing. Do you have any experience with JupyterHub? It's not really needed for this, but I'm curious.

I apparently signed in while Don was still in the middle of setting things up, so my set up may not have been what it was supposed to be. Can you follow Don's steps and confirm that you get what he expects? Basically:
- Go to https://goo.gl/AFc2pd (FYI, a temporary url) and sign in / authenticate with your github credentials
- Once you're on Jupyter, go to a terminal and double that:
  - You have a home path that looks like /home/\<github handle\> (/home/ocefpaf ?)
  - This directory was created: /home/\<github handle\>/tutorial_contents

I've already confirmed that the `odm2client` conda envs Don set up is available and working.

There's some additional information at #3 

**NOTE, 11/2:** This description needs to be updated. For example, the home path will be `/home/jovyan`, the same user name for every user, though not actually shared disk space.

**Comment by ocefpaf** [comment]
> Do you have any experience with JupyterHub?

Sadly no. The costs, time and could machinery, makes it easier to just sit down and help students get their own machines ready for classes. There is also a plus side that the students will leave class with everything they need to continue learning after the workshop is done. (That is the Software Carpentry way, but I understand the need for jupyterhub.)

> It's not really needed for this, but I'm curious.

Phew :sweat_smile: 

> Go to https://goo.gl/AFc2pd (FYI, a temporary url) and sign in / authenticate with your github credentials

Right after that I get:

![screenshot from 2017-10-24 16-12-48](https://user-images.githubusercontent.com/950575/31963239-6ad68a70-b8d6-11e7-9e04-2d7457711717.png)

**Comment by emiliom** [comment]
Well, that was fast ... I guess @lsetiawan needs to add users to a whitelist he mentioned. In Don's absence this week, I'll ask our local JupyterHub guru who's offered to help us.

> Sadly no. The costs, time and could machinery, makes it easier to just sit down and help students get their own machines ready for classes. There is also a plus side that the students will leave class with everything they need to continue learning after the workshop is done. 

Absolutely. But we'll strive to ensure that all or most of what we set up on JupyterHub is actually available on github (notebooks, conda envs, data files, instructions) and doable locally. But for a 2-day workshop we don't want to deal with the time it takes to help everyone get their local set up in order.

And we can afford the cloud cost, for this one-time event.

Thanks.

**Comment by lsetiawan** [comment]
> Right after that I get:

@ocefpaf please try logging in again tomorrow, let me know if that works. Thanks! 😄

**Comment by emiliom** [comment]
Thanks, @lsetiawan! Hopefully it'll work just fine for @ocefpaf.

**Comment by ocefpaf** [comment]
> @ocefpaf please try logging in again tomorrow, let me know if that works. Thanks! :smile:

It worked :tada: 

> You have a home path that looks like /home/ (/home/ocefpaf ?)

No, but I don't think that's work jupyterhub work. I get the default user, `jovyan`, but on own my instance, so no clashes are expected.

> This directory was created: /home//tutorial_contents

Nope. I guess that lives on your instance. (I do know that there is a way to share the same instance and collaborate on it, Brian Granger presented that at JupyterCon, but I don't know how to do it.)

> I've already confirmed that the odm2client conda envs Don set up is available and working.

:+1: everything seems with with the kernels.
Awesome work @lsetiawan!

**Comment by lsetiawan** [comment]
> It worked.

Thanks @ocefpaf for doing some testing for me. I'm glad it worked. 😄 

> No, but I don't think that's work jupyterhub work. I get the default user, jovyan, but on own my instance, so no clashes are expected.

Yea it should be `/home/jovyan`, because each user is basically made exactly from the same Docker image.

> Nope. I guess that lives on your instance. (I do know that there is a way to share the same instance and collaborate on it, Brian Granger presented that at JupyterCon, but I don't know how to do it.)

I guess this is still haven't been figured out completely by the developer. "There is work in progress for improving this behavior.", copying a folder from the docker container to the persistent volume.

Another way we can do this is if I go one by one cloning the repo to each user. I'll consult with Amanda and see if she knows another way. Thanks! Also I've made @emiliom and @ocefpaf admin for the jupyterhub. So, you should be able to see all the users.

**Comment by emiliom** [comment]
Thanks, @lsetiawan

**Comment by emiliom** [comment]
So, to continue this planning:

> Another way we can do this is if I go one by one cloning the repo to each user. I'll consult with Amanda and see if she knows another way.

Yup, that's basically the way we'll do it. But at least half of the participants should be able to do the cloning very easily on their own, at the JupyterHub terminal. And we can have someone else (in addition to you) helping with the set up for people.

**Comment by emiliom** [comment]
Closing. All issues on this issue have been addressed, and all relevant info discussed here has been incorporated into documentation.
