### ISSUE TITLE
Getting the 3 "USGS" ODM2 notebooks (from HydroShare) to work on our odm2client env

### ISSUE THREAD

**Issue by emiliom** [BiG-CZ/wshp2017_tutorial_content#5]
I'm working through the 3 ODM2 notebooks Jeff et al put together for the USGS demo last April/May. See https://github.com/BiG-CZ/bigcz_wshp2017#odm2-jupyter-notebooks for more details and links to these notebooks.

My goal is to have them work on our `odm2client` conda environment. Initially, I'm doing this locally (on my laptop), but if I can make it work there, it should work on JupyterHub too.

- I got the *Example1* notebook working already, after tweaks to the code.
- As of 10/24 3pm PT, I'm stuck on *Example2*, on reading the Excel YODA file using YODA-Tools `ExcelInput`. Looks like `ExcelInput` is not available on the `yodatools` conda package. Will have to wait until Stephanie's YODA-Tools dev branch is merged into master (in addition to Filipe's PR's), a release is issued, and a new conda package is generated.
- *Example3* only relies on `odm2api`. I got it working, after tweaks to the code. As it uses the output from *Example2*, an ODM2 SQLite database, I tested it using the pre-generated SQLite database fil downloaded from HydroShare.

*Updated:* Example 3 is now working.

**Comment by emiliom** [comment]
PR #6 was the first step in loading these notebooks. Just to make them available here. They **will** change as we craft the agenda and content.

**Comment by emiliom** [comment]
For what it's worth: I cloned this repo into my JupyterHub space, and was able to run the Example1 and Example3 notebooks right away! (after just updating the hard-wired file paths I'm using for now). Very cool!!!!

**Comment by lsetiawan** [comment]
Great! I think this might be what he have to do for the workshop, for everyone to clone the repo into their user space. Unless I found a way to have those setup already in their home directory. I'll have to consult with Amanda for that configuration. Thanks for trying out the environment, good to know they work! :D

**Comment by emiliom** [comment]
Yeah. We won't be giving full-blown `git` intros at the workshop, but asking people to run the `git clone` line to run on the JupyterHub terminal is not a burden. 

It may not even be worth your time investigating whether you can do it for everyone in advance. Besides, for those participants who know nothing about git/github, that may be an interesting, extra learning experience (and something they'll want to know if they want to run our tutorials locally during or after the workshop).

**Comment by lsetiawan** [comment]
> Besides,  for those participants who know nothing about git/github, that may be  an interesting, extra learning experience (and something they'll want to  know if they want to run our tutorials locally during or after the  workshop).

Yea that makes sense. I think we should quickly go through the basics of git and then point people to [geohackweek git tutorial](https://geohackweek.github.io/Introductory/03-git-tutorial/) if they wanna learn more!

**Comment by emiliom** [comment]
These 3 notebooks now work. I may still polish Examples 1 and 2, but only the text, not the code. 

Closing the issue.
